server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://tnmykmroixdwlv:11281548bb753342149896c27f14a0672a195f9caa79edce847dbd04309fbcaf@ec2-34-230-115-172.compute-1.amazonaws.com:5432/d8rq3ucgvu7i1q
    username: tnmykmroixdwlv
    password: 11281548bb753342149896c27f14a0672a195f9caa79edce847dbd04309fbcaf
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para a Dev Week pré Bootcamp Santander - DIO (Back-end)
  version: 1.1
